name: Push Docker Image to AWS ECR

on:
  push:
    branches:
      - master 

env:
  AWS_REGION: ap-south-1 
  ECR_REPO: ${{ secrets.ECR_REPO }} 
  IMAGE_TAG: ${{ github.run_number }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ {{ secrets.reg }}

      - name: Build and tag Docker image
        run: docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} .

      - name: Tag the image with ECR registry URL
        run: docker tag ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} ${{ secrets.reg }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.reg }}/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
